### ISSUE TITLE
Update default sim to use AMP kart

### ISSUE THREAD

**Issue by alanssitis** [Autonomous-Motorsports-Purdue/AMP_ASSV3#10]
## Description
Update default sim to use AMP kart instead of tb3 waffle robot.

## Tasks

- [ ] Remove waffle robot
- [ ] Add AMP kart URDF model
- [ ] Add AMP kart Gazebo model
- [ ] Add AMP kart Gazebo model to sim

## Resources

- https://docs.ros.org/en/foxy/Tutorials/Intermediate/URDF/URDF-Main.html

**Comment by alanssitis** [comment]
Fixed a while back I think
