### ISSUE TITLE
Create a parser to check integrity of Device Tree documentation.

### ISSUE THREAD

**Issue by alanssitis** [Autonomous-Motorsports-Purdue/AMP_ASSV3#6]
## Description

Create a python script that will go into each package and make sure all `amp` packages have their `Device Tree` section updated accordingly.

Place script under `/scripts`.

## Tasks

- [ ] Create comment wrappers around list
- [ ] Parse list into an adequate representation
- [ ] Verify representation
- [ ] Provide adequate feedback
- [ ] Test extensively
- [ ] Add to CI

**Comment by alanssitis** [comment]
Feels like a fun weekend project that should take me a day or two :smile:.
